package com.bizlama.api.outbox;

import java.time.Instant;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Input to {@link TransactionalOutboxService#append(OutboxEventDraft)}.
 * Blank optional ids/timestamps are generated by the service.
 */
public record OutboxEventDraft(
        String eventId,
        String eventType,
        Integer schemaVersion,
        String kitchenId,
        String entityType,
        String entityId,
        Instant occurredAt,
        String correlationId,
        String causationId,
        String deduplicationKey,
        Object payload,
        Map<String, ?> sourceMetadata
) {
    public OutboxEventDraft {
        sourceMetadata = sourceMetadata == null
                ? Map.of()
                : Collections.unmodifiableMap(
                        new LinkedHashMap<>(sourceMetadata));
    }

    public static OutboxEventDraft v1(
            String eventType,
            String kitchenId,
            String entityType,
            String entityId,
            String deduplicationKey,
            Object payload) {

        return new OutboxEventDraft(
                null,
                eventType,
                1,
                kitchenId,
                entityType,
                entityId,
                null,
                null,
                null,
                deduplicationKey,
                payload,
                Map.of());
    }
}
